AWSTemplateFormatVersion: 2010-09-09
Description: Create a simple EC2 instance with security group

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::key-pair.pem
    Description: Key pair to connect to the instance
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-080c353f4798a202f # Amazon Linux 2 AMI (us-east-1)
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

Outputs:
  InstanceId:
    Description: The ID of the created EC2 instance
    Value: !Ref MyEC2Instance
